name: Java CI - PhysicsMenuCalculator

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # 수동 실행 가능

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      # 1. 소스코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. JDK 17 설치 (Codespaces 기본적으로 JDK 있지만, 명시적으로 설정)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Java 컴파일
      - name: Compile Java program
        run: |
          javac -encoding UTF-8 PhysicsMenuCalculator.java

      # 4. Java 실행 (입력 자동 주입)
      - name: Run Java program
        run: |
          echo "9\n0\n" | java -Xms3m -Xmx5m PhysicsMenuCalculator
